import Head from 'next/head';
import Jumbotron from '../components/Jumbotron/Jumbotron';
import Nav from '../components/Nav/Nav';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cats App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Nav />
        <Jumbotron />
      </main>
    </div>
  );
}
